###hello word
GET http://localhost:8080/hello


###hello word
POST http://localhost:8080/api/genai/chat
Content-Type: application/json

{"prompt":"你好"}


###hello word
POST http://localhost:8080/api/genai/chat2
Content-Type: application/json

{
  "prompt":"你是誰",
  "system":""
}

###"gemma3:27b
POST http://localhost:11434/api/chat
Content-Type: application/json

{
  "model": "gemma3:27b",
  "messages": [
    {
      "role": "user",
      "content": "你好"
    }
  ]
}

###"gemma3
POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "gemma3:12b",
  "system": "你是一個精通中文的助手，請用繁體中文回答所有問題。",
  "prompt": "gemma3是什麼",
  "stream": false
}
