version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-UTC8-c
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "jpa_mysql"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jpa_mysql_app-c
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/jpa_mysql?serverTimezone=Asia/Taipei&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "123456"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  db_data:
    driver: local

