###根據USER_ID取得使用者個人檔案
GET https://api.line.me/v2/bot/profile/{{lineBotUserIdT450}}
Authorization: Bearer {{lineBotBearer}}

###抓linebot的好友列表-不能用
GET https://api.line.me/v2/bot/followers/ids
Authorization: Bearer {{lineBotBearer}}

###抓linebot的好友列表-不能用
GET https://api.line.me/v2/bot/followers/ids?start=&limit=200
Authorization: Bearer {{lineBotBearer}}

###帳號測試
GET https://api.line.me/v2/bot/info
Authorization: Bearer {{lineBotBearer}}

###發多個推播給單人-OK
POST https://api.line.me/v2/bot/message/push
Authorization: Bearer {{lineBotBearer}}
Content-Type: application/json

{
  "to": "{{lineBotUserIdRex}}",
  "messages":[
    {
      "type":"text",
      "text":"Hello, world1"
    },
    {
      "type":"text",
      "text":"Hello, world2"
    }
  ]
}

###發推播給多人-能成功
POST https://api.line.me/v2/bot/message/multicast
Authorization: Bearer {{lineBotBearer}}
Content-Type: application/json

{
  "to": ["{{lineBotUserIdRex}}","{{lineBotUserIdYuWei}}"],
  "messages": [
    {
      "type": "text",
      "text": "大家好~~~"
    }
  ]
}

###發推播給多人-圖片-能成功
POST https://api.line.me/v2/bot/message/multicast
Authorization: Bearer {{lineBotBearer}}
Content-Type: application/json

{
  "to": ["{{lineBotUserIdRex}}","{{lineBotUserIdYuWei}}"],
  "messages": [
    {
      "type": "image",
      "originalContentUrl": "{{originalContentUrl}}",
      "previewImageUrl": "{{previewImageUrl}}"
    }
  ]
}