spring.application.name=JwtDemo

# JWT Configuration
jwt.secret=mySecretKeyForJwtTokenGenerationAndValidation12345678
# Token ??? (??) - 1??
jwt.expiration=3600000

# Server Configuration
server.port=8080

