spring.application.name=LinebotDemo
server.port=8080


#line
line.bot.channel-token=
line.bot.channel-secret=
line.bot.handler.enabled=true
line.bot.handler.path=/callback

##test
#test.test-name = Url
#test.test-url = url123


