spring.application.name=LinebotDemo
server.port=8080


#line
line.bot.channel-token=2BifHnyTmiATRIO0f9nWC4RH3pntpRds4U1CPtq7YKHnsskg7dGII3CqsldkH/W+AuyGEm2qlUHTXPPuCcHRm/oUHD9aBJBe9ic4tkOqkfQdjCRTnrOHOgZKXOSayVig2Bxl14md99E6ybWFC7U6NQdB04t89/1O/w1cDnyilFU=
line.bot.channel-secret=4d5e0bcbe16ddbd53abed7d49bdb92de
line.bot.handler.enabled=true
line.bot.handler.path=/callback

##test
#test.test-name = Url
#test.test-url = url123


